image: gradle:8.12.1-jdk21

stages:
  - test

test:
  stage: test
  tags:
    - students-buildkit-medium
  script:
    - ./gradlew test --info
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml
    paths:
      - build/test-results/
      - build/reports/
    when: always
  cache:
    paths:
      - .gradle/
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "dev"'
